# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
notifications:
  email: false
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/shashi/ComputeFramework.jl.git"); Pkg.build("ComputeFramework")' # Until ComputeFramework is registered.
 - julia -e 'Pkg.clone(pwd()); Pkg.build("ParallelGraphs"); Pkg.test("ParallelGraphs"; coverage=true)'
